# Generated by Django 6.0.1 on 2026-01-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentproject',
            name='image_url',
        ),
        migrations.AddField(
            model_name='studentproject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='student_projects/'),
        ),
    ]
