# Generated by Django 6.0.1 on 2026-01-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_studentproject_image_url_studentproject_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement', models.CharField(max_length=200)),
                ('student_name', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
