# Generated by Django 6.0.1 on 2026-01-29 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentachievement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentproject',
            name='student_author',
        ),
        migrations.AddField(
            model_name='studentproject',
            name='awards',
            field=models.TextField(blank=True, help_text='Comma-separated awards'),
        ),
        migrations.AddField(
            model_name='studentproject',
            name='project_type',
            field=models.CharField(choices=[('Capstone', 'Capstone'), ('Research', 'Research')], default='Capstone', max_length=50),
        ),
        migrations.AddField(
            model_name='studentproject',
            name='semester',
            field=models.CharField(default='2023-2024', max_length=20),
        ),
        migrations.AddField(
            model_name='studentproject',
            name='team_members',
            field=models.CharField(default='', help_text='Comma-separated names', max_length=500),
        ),
        migrations.AddField(
            model_name='studentproject',
            name='technologies',
            field=models.TextField(default='', help_text='Comma-separated technologies (e.g., Arduino, React)'),
        ),
        migrations.AddField(
            model_name='studentproject',
            name='track',
            field=models.CharField(choices=[('IoT', 'Internet of Things'), ('Embedded Systems', 'Embedded Systems')], default='IoT', max_length=50),
        ),
        migrations.AddField(
            model_name='studentproject',
            name='year_level',
            field=models.CharField(default='4th Year', help_text="e.g., '4th Year' or '3rd Year'", max_length=20),
        ),
    ]
