# Generated by Django 6.0.1 on 2026-01-29 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_remove_studentproject_student_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicScholar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year_level', models.CharField(choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year')], default='1st Year', max_length=20)),
                ('gpa', models.DecimalField(decimal_places=2, help_text='Grade Point Average (1.00 - 5.00)', max_digits=4)),
            ],
        ),
    ]
