# Generated by Django 6.0.1 on 2026-01-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_academicscholar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year', models.IntegerField(help_text='Graduation Year (e.g. 2023)')),
                ('track', models.CharField(blank=True, help_text='Track for Undergrads (e.g. IoT, Embedded Systems)', max_length=100)),
                ('program_type', models.CharField(choices=[('Undergraduate', 'Undergraduate'), ('Graduate', 'Graduate')], default='Undergraduate', max_length=20)),
                ('awards', models.TextField(blank=True, help_text='Comma-separated awards')),
                ('thesis', models.CharField(max_length=300)),
                ('presentation', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Alumni',
                'ordering': ['-year', 'program_type', 'name'],
            },
        ),
    ]
