# Generated by Django 6.0.1 on 2026-01-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alumni'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentproject',
            name='status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Ongoing', max_length=20),
        ),
    ]
