# Generated by Django 6.0.1 on 2026-01-29 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_studentproject_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentResearchProject',
            fields=[
            ],
            options={
                'verbose_name': 'Student Research Project',
                'verbose_name_plural': 'Student Research Projects',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('students.studentproject',),
        ),
    ]
