# Generated by Django 6.0.1 on 2026-01-29 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_studentresearchproject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentResearchProject',
        ),
    ]
