# Generated by Django 6.0.1 on 2026-02-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_delete_studentresearchproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicscholar',
            name='gpa',
            field=models.DecimalField(decimal_places=4, help_text='Grade Point Average (1.00 - 5.00)', max_digits=4),
        ),
    ]
