# Generated by Django 6.0.1 on 2026-03-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_academicscholar_gpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentproject',
            name='abstract',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='studentproject',
            name='link_input',
            field=models.URLField(blank=True, help_text='Link to publication'),
        ),
        migrations.AddField(
            model_name='studentproject',
            name='paper_presented',
            field=models.CharField(blank=True, help_text='Conference Name, if presented (applies when Completed)', max_length=300),
        ),
        migrations.AddField(
            model_name='studentproject',
            name='pdf_upload',
            field=models.FileField(blank=True, help_text='Upload full paper (PDF)', null=True, upload_to='research_papers/'),
        ),
        migrations.AddField(
            model_name='studentproject',
            name='publish_journals',
            field=models.CharField(blank=True, help_text='Journal Name, if published', max_length=300),
        ),
        migrations.AlterField(
            model_name='studentproject',
            name='team_members',
            field=models.CharField(default='', help_text='Comma-separated names (including Faculty Adviser)', max_length=500),
        ),
    ]
