# Generated by Django 6.0.1 on 2026-03-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_studentproject_abstract_studentproject_link_input_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentproject',
            name='link_input',
            field=models.TextField(blank=True, help_text='Comma-separated links to publications (e.g., https://link1.com, https://link2.com)'),
        ),
    ]
