# Generated by Django 6.0.1 on 2026-03-22 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_alter_studentproject_link_input'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentproject',
            name='link_input',
        ),
        migrations.RemoveField(
            model_name='studentproject',
            name='publish_journals',
        ),
        migrations.CreateModel(
            name='StudentProjectPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_name', models.CharField(max_length=300)),
                ('link', models.URLField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='students.studentproject')),
            ],
        ),
    ]
