# Generated by Django 6.0.1 on 2026-03-22 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_remove_studentproject_link_input_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentproject',
            name='paper_presented',
        ),
        migrations.CreateModel(
            name='StudentProjectPresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference_name', models.CharField(max_length=300)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='students.studentproject')),
            ],
        ),
    ]
