# Generated by Django 6.0.1 on 2026-03-22 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_remove_studentproject_paper_presented_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentprojectpresentation',
            options={'verbose_name': 'Presentation', 'verbose_name_plural': 'Presentations'},
        ),
        migrations.AlterModelOptions(
            name='studentprojectpublication',
            options={'verbose_name': 'Publication', 'verbose_name_plural': 'Publications'},
        ),
    ]
