# Generated by Django 6.0.1 on 2026-03-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_alter_studentprojectpresentation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentproject',
            name='is_masters',
            field=models.BooleanField(default=False, help_text="Check if this is a Master's project (hides track & year level)", verbose_name="Is Master's Project"),
        ),
        migrations.AlterField(
            model_name='studentproject',
            name='project_type',
            field=models.CharField(choices=[('Project', 'Project'), ('Research', 'Research')], default='Project', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentproject',
            name='track',
            field=models.CharField(blank=True, choices=[('IoT', 'Internet of Things'), ('Embedded Systems', 'Embedded Systems')], default='IoT', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentproject',
            name='year_level',
            field=models.CharField(blank=True, choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year')], default='4th Year', help_text="Leave blank if Master's", max_length=20),
        ),
    ]
