# Generated by Django 6.0.1 on 2026-03-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0012_focusarea'),
        ('students', '0017_studentproject_is_masters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentproject',
            name='focus_areas',
            field=models.ManyToManyField(blank=True, help_text='Used primarily for Student Research (Theses).', related_name='student_projects', to='research.focusarea'),
        ),
        migrations.AlterField(
            model_name='studentproject',
            name='awards',
            field=models.TextField(blank=True, default='', help_text='Comma-separated awards (if any)'),
        ),
    ]
