# Generated by Django 6.0.1 on 2026-01-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('research_interests', models.JSONField(blank=True, default=list)),
                ('bio', models.TextField(blank=True)),
                ('image', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('office', models.CharField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Faculty Members',
                'ordering': ['name'],
            },
        ),
    ]
