# Generated by Django 6.0.1 on 2026-01-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultymember',
            name='networks',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='facultymember',
            name='research_interests',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
