# Generated by Django 6.0.1 on 2026-01-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_alter_facultymember_networks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultymember',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='faculty_images/'),
        ),
    ]
