# Generated by Django 6.0.1 on 2026-01-28 01:13

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_facultymember_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultymember',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('profile_image', '400x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
