# Generated by Django 6.0.1 on 2026-01-28 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_facultymember_cropping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
            ],
            options={
                'verbose_name': 'Lecturer',
                'verbose_name_plural': 'Lecturers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('faculty.facultymember',),
        ),
        migrations.CreateModel(
            name='RegularFaculty',
            fields=[
            ],
            options={
                'verbose_name': 'Regular Faculty',
                'verbose_name_plural': 'Regular Faculties',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('faculty.facultymember',),
        ),
        migrations.CreateModel(
            name='SupportStaff',
            fields=[
            ],
            options={
                'verbose_name': 'Support Staff',
                'verbose_name_plural': 'Support Staff',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('faculty.facultymember',),
        ),
    ]
