# Generated by Django 6.0.1 on 2026-01-29 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0005_lecturer_regularfaculty_supportstaff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regularfaculty',
            options={'verbose_name': 'Faculty Member', 'verbose_name_plural': 'Faculty Members'},
        ),
        migrations.CreateModel(
            name='FacultyResearchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Ongoing', max_length=20)),
                ('lead_researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_projects', to='faculty.facultymember')),
            ],
        ),
    ]
