# Generated by Django 6.0.1 on 2026-01-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0006_alter_regularfaculty_options_facultyresearchproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultymember',
            name='faculty_type',
            field=models.CharField(choices=[('Core', 'Core Faculty'), ('Adjunct', 'Adjunct Faculty')], default='Core', max_length=20),
        ),
    ]
