# Generated by Django 6.0.1 on 2026-03-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0007_facultymember_faculty_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyresearchproject',
            name='research_category',
            field=models.CharField(choices=[('MS', 'MS Thesis'), ('PhD', 'PhD Dissertation'), ('Faculty/Funded', 'Faculty / Funded Research')], default='Faculty/Funded', max_length=50),
        ),
    ]
