# Generated by Django 6.0.1 on 2026-03-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0008_facultyresearchproject_research_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyresearchproject',
            name='abstract',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='facultyresearchproject',
            name='technologies',
            field=models.CharField(blank=True, help_text='Comma-separated technologies (e.g., Python, React)', max_length=500),
        ),
    ]
