# Generated by Django 6.0.1 on 2026-01-29 10:50

import resources_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Student Academic Forms', 'Student Academic Forms'), ('Research & Thesis', 'Research & Thesis'), ('Administrative Documents', 'Administrative Documents')], default='Student Academic Forms', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description of the document')),
                ('file', models.FileField(upload_to='resources/', validators=[resources_app.validators.validate_file_extension])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
    ]
