# Generated by Django 6.0.1 on 2026-01-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='degree',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='program',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='program',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='programs/'),
        ),
        migrations.AddField(
            model_name='program',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='careers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='outcome',
            field=models.TextField(blank=True),
        ),
    ]
