# Generated by Django 6.0.1 on 2026-01-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_program_degree_program_features_program_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curriculumcourse',
            options={'ordering': ['year', 'semester', 'code']},
        ),
        migrations.AddField(
            model_name='program',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='degree',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='program_images/'),
        ),
        migrations.AlterField(
            model_name='program',
            name='outcome',
            field=models.TextField(blank=True, null=True),
        ),
    ]
