# Generated by Django 6.0.1 on 2026-01-28 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_curriculumcourse_options_program_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='features',
            new_name='key_focus_areas',
        ),
    ]
