# Generated by Django 6.0.1 on 2026-01-28 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_rename_features_program_key_focus_areas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('vision', models.TextField(blank=True, null=True)),
                ('mission', models.TextField(blank=True, null=True)),
                ('goals_objectives', models.TextField(blank=True, null=True, verbose_name='Goals & Objectives')),
                ('core_competencies', models.TextField(blank=True, null=True, verbose_name='Core Competencies')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='academics.program')),
            ],
        ),
    ]
