# Generated by Django 6.0.1 on 2026-01-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='mission_image',
            field=models.ImageField(blank=True, null=True, upload_to='track_images/'),
        ),
        migrations.AddField(
            model_name='track',
            name='vision_image',
            field=models.ImageField(blank=True, null=True, upload_to='track_images/'),
        ),
    ]
