# Generated by Django 6.0.1 on 2026-01-28 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_track_mission_image_track_vision_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='core_competencies',
        ),
        migrations.RemoveField(
            model_name='track',
            name='goals_objectives',
        ),
        migrations.RemoveField(
            model_name='track',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='track',
            name='name',
        ),
        migrations.CreateModel(
            name='TrackCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='competency_icons/')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='academics.track')),
            ],
        ),
        migrations.CreateModel(
            name='TrackGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Goals & Objectives', max_length=200)),
                ('goal_points', models.JSONField(default=list, verbose_name='Goal Points (List)')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='academics.track')),
            ],
        ),
        migrations.CreateModel(
            name='TrackMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Mission', max_length=200)),
                ('mission_points', models.JSONField(default=list, verbose_name='Mission Points (List)')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='academics.track')),
            ],
        ),
    ]
