# Generated by Django 6.0.1 on 2026-01-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_remove_track_core_competencies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='name',
            field=models.CharField(default='Standard Track', max_length=200),
            preserve_default=False,
        ),
    ]
