# Generated by Django 6.0.1 on 2026-01-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_track_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackgoal',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='trackmission',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
