# Generated by Django 6.0.1 on 2026-01-29 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0006_alter_regularfaculty_options_facultyresearchproject'),
        ('research', '0002_remove_researchproject_image_url_and_more'),
        ('students', '0009_delete_studentresearchproject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResearchProject',
        ),
        migrations.CreateModel(
            name='FacultyResearchProject',
            fields=[
            ],
            options={
                'verbose_name': 'Faculty Research Project',
                'verbose_name_plural': 'Faculty Research Projects',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('faculty.facultyresearchproject',),
        ),
        migrations.CreateModel(
            name='StudentResearchProject',
            fields=[
            ],
            options={
                'verbose_name': 'Student Research Project',
                'verbose_name_plural': 'Student Research Projects',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('students.studentproject',),
        ),
    ]
