# Generated by Django 6.0.1 on 2026-03-22 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_delete_researchproject_facultyresearchproject_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facultyresearchproject',
            options={'verbose_name': 'Faculty Research', 'verbose_name_plural': 'Faculty Research'},
        ),
        migrations.AlterModelOptions(
            name='studentresearchproject',
            options={'verbose_name': 'Student Projects', 'verbose_name_plural': 'Student Projects'},
        ),
    ]
