# Generated by Django 6.0.1 on 2026-03-22 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_alter_facultyresearchproject_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentresearchproject',
            options={'verbose_name': 'Student Research', 'verbose_name_plural': 'Student Research'},
        ),
    ]
