# Generated by Django 6.0.1 on 2026-03-22 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_alter_studentresearchproject_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facultyresearchproject',
            options={'verbose_name': 'Ongoing Faculty Research', 'verbose_name_plural': 'Ongoing Faculty Research'},
        ),
    ]
