# Generated by Django 6.0.1 on 2026-03-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0006_alter_facultyresearchproject_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchStatisticsOffset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_publications', models.IntegerField(default=0, help_text='Added to the dynamically calculated Publications count.')),
                ('base_awards', models.IntegerField(default=0, help_text='Added to the dynamically calculated Awards count.')),
                ('base_active_projects', models.IntegerField(default=0, help_text='Added to the dynamically calculated Active Projects count.')),
            ],
            options={
                'verbose_name': 'Research Statistics Offset',
                'verbose_name_plural': 'Research Statistics Offsets',
            },
        ),
    ]
