# Generated by Django 6.0.1 on 2026-03-22 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0008_collaborator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborator',
            name='website',
        ),
    ]
