# Generated by Django 6.0.1 on 2026-03-22 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0009_remove_collaborator_website'),
        ('students', '0017_studentproject_is_masters_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentBuiltProject',
            fields=[
            ],
            options={
                'verbose_name': 'Student Project',
                'verbose_name_plural': 'Student Projects',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('students.studentproject',),
        ),
        migrations.AlterModelOptions(
            name='studentresearchproject',
            options={'verbose_name': 'Student Research (Thesis)', 'verbose_name_plural': 'Student Research (Thesis)'},
        ),
    ]
