# Generated by Django 6.0.1 on 2026-03-22 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0009_facultyresearchproject_abstract_and_more'),
        ('research', '0010_studentbuiltproject_and_more'),
        ('students', '0017_studentproject_is_masters_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FacultyResearchProject',
        ),
        migrations.DeleteModel(
            name='StudentResearchProject',
        ),
        migrations.CreateModel(
            name='FacultyResearch',
            fields=[
            ],
            options={
                'verbose_name': 'Ongoing Faculty Research',
                'verbose_name_plural': 'Ongoing Faculty Research',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('faculty.facultyresearchproject',),
        ),
        migrations.CreateModel(
            name='StudentResearch',
            fields=[
            ],
            options={
                'verbose_name': 'Student Research (Thesis)',
                'verbose_name_plural': 'Student Research (Thesis)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('students.studentproject',),
        ),
    ]
