# Generated by Django 6.0.1 on 2026-03-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0011_delete_facultyresearchproject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FocusArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(help_text="e.g. 'ai-ml'", max_length=200, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Focus Area',
                'verbose_name_plural': 'Focus Areas',
            },
        ),
    ]
