# Generated by Django 6.0.1 on 2026-03-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0012_focusarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchstatisticsoffset',
            name='h_index_department',
            field=models.IntegerField(default=0, help_text='H-Index (Department)'),
        ),
        migrations.AddField(
            model_name='researchstatisticsoffset',
            name='scopus_publications',
            field=models.IntegerField(default=0, help_text='Total Scopus publications'),
        ),
    ]
