# Generated by Django 6.0.1 on 2026-03-22 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0013_researchstatisticsoffset_h_index_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchstatisticsoffset',
            name='funded_projects',
            field=models.IntegerField(default=0, help_text='Total number of funded projects'),
        ),
        migrations.AddField(
            model_name='researchstatisticsoffset',
            name='publications_per_faculty_current',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Current Publications per Faculty (e.g., 1.5)', max_digits=5),
        ),
        migrations.AddField(
            model_name='researchstatisticsoffset',
            name='publications_per_faculty_target',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Target Publications per Faculty (e.g., 2.0)', max_digits=5),
        ),
        migrations.AddField(
            model_name='researchstatisticsoffset',
            name='research_funding',
            field=models.BigIntegerField(default=0, help_text='Total Research Funding in Pesos (e.g., 6098999)'),
        ),
    ]
