# Generated by Django 6.0.1 on 2026-01-29 10:24

import image_cropping.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtensionProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Upcoming', 'Upcoming'), ('Completed', 'Completed')], default='Ongoing', max_length=20)),
                ('category', models.CharField(choices=[('Community Impact', 'Community Impact'), ('Technology Education', 'Technology Education'), ('Skills Development', 'Skills Development'), ('Innovation', 'Innovation')], default='Community Impact', max_length=50)),
                ('date', models.CharField(help_text="e.g. 'January 2025' or 'Monthly'", max_length=50)),
                ('beneficiaries_count', models.IntegerField(default=0, help_text='Number of people impacted')),
                ('beneficiaries_label', models.CharField(default='Beneficiaries', help_text="e.g. 'Students', 'Farmers'", max_length=100)),
                ('municipality', models.CharField(help_text='Location/Municipality served', max_length=100)),
                ('partner_organization', models.CharField(blank=True, help_text='Partner organization name', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='extension_images/')),
                ('cropping', image_cropping.fields.ImageRatioField('image', '800x600', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
