# Generated by Django 6.0.1 on 2026-01-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_newsitem_image_url_newsitem_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsitem',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='newsitem',
            name='category',
            field=models.CharField(choices=[('Event', 'Event'), ('Facility', 'Facility'), ('Achievement', 'Achievement'), ('General', 'General')], default='General', max_length=50),
        ),
    ]
