# Generated by Django 6.0.1 on 2026-01-28 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('batch_year', models.IntegerField()),
                ('degree', models.CharField(default='BS Computer Applications', max_length=255)),
                ('current_position', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('testimonial', models.TextField(blank=True)),
                ('image', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-batch_year', 'name'],
            },
        ),
    ]
