# Generated by Django 6.0.1 on 2026-01-29 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Undergraduate', 'Undergraduate'), ('Graduate', 'Graduate')], default='Undergraduate', max_length=20)),
                ('title', models.CharField(help_text="e.g., 'Application Period' or 'Scholarship Application'", max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, help_text='Optional extra info displayed below the date.')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'start_date'],
            },
        ),
    ]
