# Generated by Django 6.0.1 on 2026-03-22 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_admissiondeadline'),
        ('research', '0009_remove_collaborator_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryPartner',
            fields=[
            ],
            options={
                'verbose_name': 'Collaboration / Industry Partner',
                'verbose_name_plural': 'Collaborations / Industry Partners',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('research.collaborator',),
        ),
    ]
